[package]
name = "ncubectl"
version = "0.4.0"
authors = ["Christo <christo@cryptodrunks.net>"]
edition = "2018"

[dependencies]
futures = "0.3.4"
tokio = { version = "0.2", features = ["macros"] }
directories = "2.0.2"
clap = "3.0.0-beta.1"
prettytable-rs = "0.8.0"

ncubed = { path = "../ncubed" }
