[package]
name = "ncubed"
version = "0.1.0"
authors = ["Christo <christo@cryptodrunks.net>"]
edition = "2018"

[dependencies]
futures = "0.3.4"
tokio = { version = "0.2", features = ["macros", "sync", "time"] }
warp = "0.2.2"
rusqlite = "0.21.0"
refinery = { version = "0.2", features = ["rusqlite"]}
refinery-migrations = "0.2"
thiserror = "1.0"
