[package]
name = "ncubed"
version = "0.4.0"
authors = ["Christo <christo@cryptodrunks.net>"]
edition = "2018"

[dependencies]
futures = "0.3.4"
tokio = { version = "0.2", features = ["macros", "sync", "time", "rt-threaded", "process"] }
async-trait = "0.1"
thiserror = "1.0"
anyhow = "1.0"
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_rusqlite = "0.23.0"
xactor = { git = "https://github.com/critocrito/xactor.git", branch = "tokio-runtime", default-features = false, features = ["runtime-tokio"] }
once_cell = "1.3.1"
fnv = "1.0.6"
warp = "0.2.2"
semval = "0.1.3"
deadpool = "0.5.1"
deadpool-postgres = "0.5.5"
rusqlite = { version = "0.21.0", features = ["bundled"] }
refinery = { version = "0.2", features = ["rusqlite"]}
refinery-migrations = "0.2"
time = { version = "0.2", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
slugify = "0.1.0"
dirs = "2.0.2"
flate2 = "1.0.14"
tar = "0.4.26"
rand = "0.7.3"
rust-argon2 = "0.8.2"
hmac = "0.7.1"
sha2 = "0.8.2"
jwt = "0.7.0"

ncube-data = { path = "../ncube-data" }

[dev-dependencies]
tokio-test = "0.2"
