name: Build Status
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  ci:
    env:
      RUST_BACKTRACE: 1
    runs-on: ${{ matrix.os }}
    name: ci

    strategy:
      matrix:
        # FIXME: Windows builds are missing.
        build: [stable-bionic, stable-focal, beta, nightly, macos]
        include:
          - build: stable-bionic
            os: ubuntu-18.04
            rust: stable
          - build: stable-focal
            os: ubuntu-20.04
            rust: stable
          - build: beta
            os: ubuntu-20.04
            rust: beta
          - build: nightly
            os: ubuntu-20.04
            rust: nightly
          - build: macos
            os: macos-latest
            rust: stable

    steps:
    - uses: actions/checkout@v2

    - name: Install packages (Ubuntu)
      if: matrix.os == 'ubuntu-18.04' || matrix.os == 'ubuntu-20.04'
      run: scripts/ci/ubuntu-install-packages

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
        override: true
        components: rustfmt

    - name: Install Node dependencies
      run: yarn install

    - name: Verify Ncube UI
      run: make verify-ui

    - name: Test Ncube UI
      run: make test-ui

    - name: Build Ncube UI
      run: make ui

    - name: Build Local Workspace
      run: make workspace

    # The backend requires that the ui and the workspace are built. Make sure to
    # run this task only after those.
    - name: Verify Ncube Backend
      run: make verify-backend

    - name: Test Ncube Backend
      run: make test-backend
